---
on:
  push:
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'
      - run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: luschmar/go-wunderground-exporter:${{ steps.get_version.outputs.VERSION }},luschmar/go-wunderground-exporter:latest
