on:
  push:
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Build go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20.3' # The Go version to download (if necessary) and use.
      - run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: luschmar/go-wunderground-exporter:${{ steps.get_version.outputs.VERSION }},luschmar/go-wunderground-exporter:latest
